name: Dev Build and Release

on:
  push:
    branches-ignore:
      - 'release'

jobs:
  branch_meta:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch_meta.outputs.branch }}
      sha: ${{ steps.extract_branch_meta.outputs.sha }}
    steps:
      - name: Extract branch meta
        shell: bash
        id: extract_branch_meta
        env:
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          BRANCH_REF_NAME: ${{ github.ref_name}}
          BRANCH_SHA: ${{ github.sha }}
        run: |
          if [ "${{ github.event_name }}" == 'pull_request' ]; then
            echo "branch=$PR_HEAD_REF" >> $GITHUB_OUTPUT
            echo "sha=$PR_HEAD_SHA" >> $GITHUB_OUTPUT
          else
            echo "branch=$BRANCH_REF_NAME" >> $GITHUB_OUTPUT
            echo "sha=$BRANCH_SHA" >> $GITHUB_OUTPUT
          fi

  scan:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@5
    permissions:
      contents: read

  helm_release_sha:
    runs-on: ubuntu-latest
    concurrency:
      group: helm_release
      cancel-in-progress: false
    needs:
      - scan
      - branch_meta
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - id: lower-helm-repo
        name: Repository to lowercase
        run: |
          repo_var=${{ github.repository }}
          echo "repository=${repo_var@L}" >> $GITHUB_OUTPUT
      - name: Log into ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push helm chart to ghcr
        shell: bash
        id: extract_branch_meta
        env:
          CHART_VERSION: "0.0.1-${{ needs.branch_meta.outputs.sha }}"
          CHART_APP_VERSION: "0.0.1-${{ needs.branch_meta.outputs.sha }}"
          CHART_NAME: "mailpit"
          CHART_DIR: "charts"
        run: |
          helm version
          helm package "$CHART_DIR/$CHART_NAME" --version $CHART_VERSION --app-version $CHART_APP_VERSION
          helm push "$CHART_NAME-$CHART_VERSION.tgz" oci://ghcr.io/${{ steps.lower-helm-repo.outputs.repository }}


  helm_release_branch:
    runs-on: ubuntu-latest
    concurrency:
      group: helm_release
      cancel-in-progress: false
    needs:
      - scan
      - branch_meta
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - id: lower-helm-repo
        name: Repository to lowercase
        run: |
          repo_var=${{ github.repository }}
          echo "repository=${repo_var@L}" >> $GITHUB_OUTPUT
      - name: Log into ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push helm chart to ghcr
        shell: bash
        id: extract_branch_meta
        env:
          CHART_VERSION: "0.0.1-${{ needs.branch_meta.outputs.branch }}"
          CHART_APP_VERSION: "0.0.1-${{ needs.branch_meta.outputs.branch }}"
          CHART_NAME: "mailpit"
          CHART_DIR: "charts"
        run: |
          helm version
          helm package "$CHART_DIR/$CHART_NAME" --version $CHART_VERSION --app-version $CHART_APP_VERSION
          helm push "$CHART_NAME-$CHART_VERSION.tgz" oci://ghcr.io/${{ steps.lower-helm-repo.outputs.repository }}
